### ISSUE TITLE
Setting $TMP fails varibles not passed to subshells

### ISSUE THREAD

**Issue by marnold** [willysr/csb#4]
Hello --

  I tried setting the $TMP variable from the shell like so 
export TMP=/work/csb
Slackware package /tmp/gnome-common-3.6.0-noarch-1_csb.txz created.
Error:  package to upgrade gnome-common-3.6.0-*-1*.txz not found in /work/csb

**Comment by willysr** [comment]
Did you run the SlackBuild script manually or use the build script?

**Comment by marnold** [comment]
I was using the top level build script, but i tried it the way you suggested. And while that method doesn't cause the Slackbuild to error out it still places the generated package under /tmp/ which is not ideal, on my system. I could just set $OUTPUT but it would be nice if that was set for the parent of $TMP

**Comment by willysr** [comment]
Fixed in 9923bdf
