### ISSUE TITLE
Nemo 3.0.3 compile error

### ISSUE THREAD

**Issue by Skaendo** [willysr/csb#6]
Nemo is failing to compile for me.
Basics; Fresh full Slackware-64-current +bash-completion +wicd.
Here is what I'm getting:

make[2]: Leaving directory '/tmp/csb/nemo-3.0.3/docs/reference'
make[2]: Entering directory '/tmp/csb/nemo-3.0.3/docs'
make[3]: Entering directory '/tmp/csb/nemo-3.0.3/docs'
make[3]: Nothing to be done for 'install-exec-am' .
 /usr/bin/mkdir -p '/tmp/csb/package-nemo/usr/man/man1'
 /usr/bin/ginstall -c -m 644 nemo.1 nemo-connect-server.1 '/tmp/csb/package-nemo/usr/man/man1'
make[3]: Leaving directory 'tmp/csb/nemo-3.0.3/docs'
make[2]: Leaving directory 'tmp/csb/nemo-3.0.3/docs'
make[1]: Leaving directory 'tmp/csb/nemo-3.0.3/docs'
Making install in files
make[1]: Entering directory '/tmp/csb/nemo-3.0.3/files'
cd ../data && ./merge_action_strings && cd ../files && find -mindepth 1 -maxdepth 1 -type d -exec cp -R {} /tmp/csb/package-nemo/ \;
Traceback (most recent call last):
  File "./merge_action_strings", line 7, in <module>
    from gi.repository import GLib
ImportError: No module named 'gi'
Makefile:10: recipe for target 'install' failed
make[1]: *** [install] Error 1
make[1]: Leaving directory '/tmp/csb/nemo-3.0.3/files'
Makefile:508: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by willysr** [comment]
Fixed with cf072b7b0c8515390e63c1960d60479afe45860d and 579535cc5d7f3a0bd9e2195012f9582a96ee91bf

I forgot to push them to the repository few days ago when i upgraded nemo
